apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: civo-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: civo-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /cert-manager-webhook-civo-secrets
